version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "6203:8081"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8081"
    environment:
      - DB_HOST=db
      - DB_NAME=loan_ledger_dev
      - DB_USER=postgres
      - DB_PASSWORD=admin
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin


#password storage and other env variable go into CI/CD server env config. dp remember the way ARM used to work
