# Generated by Django 3.2.6 on 2021-08-31 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_manager', '0001_initial'),
        ('customer_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUERY_LOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('log', models.TextField()),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LOANS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=30, null=True, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period', models.IntegerField(default=0)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emi_months', models.IntegerField(default=0)),
                ('emi_months_repaid', models.IntegerField(default=0)),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount_pi', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('bankid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_manager.banks')),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_manager.customers')),
            ],
        ),
    ]
